// ─── Shared Skill Icon Utilities ──────────────────────────────────────────────
// Extracted so both CandidateProfileClient and CandidatePublicProfileView share
// the same devicon resolution logic without duplication.

export const SUPPORTED_DEVICONS = new Set([
  "cplusplus", "csharp", "fsharp", "amazonwebservices", "googlecloud", "azure",
  "tailwindcss", "nodejs", "nextjs", "react", "vuejs", "angular", "spring",
  "express", "postgresql", "mysql", "mongodb", "redis",
  "sqlite", "mariadb", "html5", "css3", "sass", "git", "github", "gitlab",
  "docker", "kubernetes", "terraform", "jenkins", "ansible", "figma", "photoshop",
  "illustrator", "xd", "premierepro", "python", "java", "kotlin", "scala", "swift",
  "objectivec", "ruby", "rails", "php", "go", "rust", "dart", "flutter",
  "typescript", "javascript", "bash", "linux", "ubuntu", "android", "apple",
  "wordpress", "jira", "slack", "trello", "graphql", "webpack",
  "babel", "gulp", "npm", "yarn", "postman", "django", "flask", "laravel",
  "symfony", "bootstrap",
  "apachespark", "matplotlib", "numpy", "opencv", "pandas", "pytorch", "tensorflow",
  "cassandra", "cloudflare", "dynamodb", "elasticsearch", "firebase", "heroku",
  "netlify", "oracle", "supabase", "vercel", "canva", "chakraui", "fastapi",
  "fastify", "grpc", "ionic", "materialui", "nestjs", "nuxt", "redux", "c",
  "matlab", "powershell", "r", "bitbucket", "confluence", "githubactions",
  "jest", "junit", "nginx", "pytest", "selenium", "swagger", "vite", "cypressio",
  "svelte"
]);

export const DEVICON_SUFFIXES: Record<string, string> = {
  "express": "original",
  "tensorflow": "original",
  "ionic": "original"
};

const SKILL_NAME_MAP: Record<string, string> = {
  "c++": "cplusplus",
  "c#": "csharp",
  "f#": "fsharp",
  "aws": "amazonwebservices",
  "amazon web services": "amazonwebservices",
  "google cloud": "googlecloud",
  "gcp": "googlecloud",
  "microsoft azure": "azure",
  "azure": "azure",
  "tailwind css": "tailwindcss",
  "tailwind": "tailwindcss",
  "node.js": "nodejs",
  "node": "nodejs",
  "next.js": "nextjs",
  "next": "nextjs",
  "react.js": "react",
  "react js": "react",
  "vue.js": "vuejs",
  "vue js": "vuejs",
  "vue": "vuejs",
  "angular.js": "angularjs",
  "angular": "angular",
  "spring boot": "spring",
  "express.js": "express",
  "expressjs": "express",
  "express": "express",
  "postgresql": "postgresql",
  "postgres": "postgresql",
  "sql server": "microsoftsqlserver",
  "mysql": "mysql",
  "mongodb": "mongodb",
  "redis": "redis",
  "sqlite": "sqlite",
  "mariadb": "mariadb",
  "html": "html5",
  "html5": "html5",
  "css": "css3",
  "css3": "css3",
  "sass": "sass",
  "scss": "sass",
  "git": "git",
  "github": "github",
  "gitlab": "gitlab",
  "docker": "docker",
  "kubernetes": "kubernetes",
  "k8s": "kubernetes",
  "terraform": "terraform",
  "jenkins": "jenkins",
  "ansible": "ansible",
  "figma": "figma",
  "photoshop": "photoshop",
  "illustrator": "illustrator",
  "xd": "xd",
  "adobe xd": "xd",
  "premiere pro": "premierepro",
  "premiere": "premierepro",
  "python": "python",
  "java": "java",
  "kotlin": "kotlin",
  "scala": "scala",
  "swift": "swift",
  "objective-c": "objectivec",
  "objective c": "objectivec",
  "ruby": "ruby",
  "rails": "rails",
  "ruby on rails": "rails",
  "php": "php",
  "go": "go",
  "golang": "go",
  "rust": "rust",
  "dart": "dart",
  "flutter": "flutter",
  "typescript": "typescript",
  "ts": "typescript",
  "javascript": "javascript",
  "js": "javascript",
  "apache spark": "apachespark",
  "matplotlib": "matplotlib",
  "numpy": "numpy",
  "opencv": "opencv",
  "pandas": "pandas",
  "pytorch": "pytorch",
  "tensorflow": "tensorflow",
  "cassandra": "cassandra",
  "cloudflare": "cloudflare",
  "dynamodb": "dynamodb",
  "elasticsearch": "elasticsearch",
  "firebase": "firebase",
  "heroku": "heroku",
  "netlify": "netlify",
  "oracle": "oracle",
  "supabase": "supabase",
  "vercel": "vercel",
  "canva": "canva",
  "chakra ui": "chakraui",
  "fastapi": "fastapi",
  "fastify": "fastify",
  "grpc": "grpc",
  "ionic": "ionic",
  "material ui": "materialui",
  "nestjs": "nestjs",
  "nuxt.js": "nuxt",
  "nuxt": "nuxt",
  "redux": "redux",
  "sveltekit": "svelte",
  "c": "c",
  "matlab": "matlab",
  "powershell": "powershell",
  "r": "r",
  "bitbucket": "bitbucket",
  "confluence": "confluence",
  "github actions": "githubactions",
  "jest": "jest",
  "junit": "junit",
  "nginx": "nginx",
  "pytest": "pytest",
  "selenium": "selenium",
  "swagger": "swagger",
  "vite": "vite",
  "cypress": "cypressio",
};

export function getSkillIconClass(skillName: string): string | null {
  const normalized = skillName.toLowerCase().trim();
  const resolved = SKILL_NAME_MAP[normalized] || normalized.replace(/\s+/g, "");
  return SUPPORTED_DEVICONS.has(resolved) ? resolved : null;
}
